/* Sutras editable catalogue. Extra product photos are hidden pending better replacements. */
window.SUTRAS = {
  "name": "Sutras by S³",
  "instagram": "https://www.instagram.com/sutras.official/",
  "whatsapp": [
    "260978865604",
    "260973668415"
  ],
  "currency": "ZMW",
  "imageryIsIllustrative": true,
  "products": [
    {
      "id": "orange-three-piece-set",
      "name": "Orange Three-Piece Kurta Set",
      "cardName": "Orange Kurta Set",
      "category": "Kurta sets",
      "color": "Orange & multicolour",
      "colorHex": "#e86a29",
      "image": "assets/images/orange-set-model-clean.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing the orange kurta with printed bottoms and a plain orange dupatta. Fit and small details are illustrative.",
      "description": "An orange kurta with a decorative neckline and leaf motifs, paired with multicoloured printed bottoms and a matching plain orange dupatta. Three pieces: the kurta (top), bottoms and dupatta (scarf).",
      "detail": "Three pieces shown · Embellished neckline · Leaf details & patterned fabric",
      "setContents": "Kurta, printed bottoms and plain orange dupatta (3 pieces)",
      "pieces": 3,
      "productType": "set",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [
        {"src":"assets/images/orange-details/neckline.webp","alt":"Generated close-up of the orange kurta neckline showing layered embroidered trim and tassel detailing.","label":"Neckline detail","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: layered neckline embroidery and tie-up tassels."},
        {"src":"assets/images/orange-details/sleeve.webp","alt":"Generated close-up of the orange kurta sleeve cuff with floral embroidery and a narrow border.","label":"Sleeve detail","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: three-quarter sleeve cuff with floral border embroidery."},
        {"src":"assets/images/orange-details/front-design.webp","alt":"Generated close-up of the orange kurta front neckline embroidery with hanging tassels.","label":"Front design","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: front embroidery, threadwork and tassel accents."},
        {"src":"assets/images/orange-details/fabric-print.webp","alt":"Generated macro-style view of the orange set fabric and multicoloured floral print.","label":"Fabric & print","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: orange cotton texture and coordinated floral print."},
        {"src":"assets/images/orange-details/hem.webp","alt":"Generated close-up of the orange kurta hem with a fine embroidered border and small motif.","label":"Hem detail","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: clean hem finish with a delicate border and motif."},
        {"src":"assets/images/orange-details/back.webp","alt":"Generated rear view close-up of the orange kurta showing the neckline edge and small back motif.","label":"Back detail","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: restrained back embroidery and neckline finishing."},
        {"src":"assets/images/orange-details/pants.webp","alt":"Generated close-up of the printed orange trousers from the three-piece set.","label":"Pant detail","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: coordinated printed bottoms with floral and geometric motifs."},
        {"src":"assets/images/orange-details/tie-up.webp","alt":"Generated close-up of orange tassel tie-up detailing with small bead accents.","label":"Tie-up detail","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: adjustable tie-up tassels with bead accents."},
        {"src":"assets/images/orange-details/embroidery-closeup.webp","alt":"Generated close-up of orange fabric showing delicate floral embroidery and border threadwork.","label":"Embroidery close-up","kind":"ai-detail","caption":"AI-generated detail illustration based on the modelled garment: fine floral embroidery and border threadwork."}
      ],
      "price": null,
      "availability": "unavailable",
      "isPreview": false
    },
    {
      "id": "pink-three-piece-set",
      "name": "Pink Three-Piece Kurta Set",
      "cardName": "Pink Kurta Set",
      "category": "Kurta sets",
      "color": "Fuchsia pink",
      "colorHex": "#d63377",
      "image": "assets/images/pink-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a fuchsia pink kurta with small gold motifs, matching pink bottoms and a tasseled dupatta. Fit and small details are illustrative.",
      "description": "A vivid pink kurta with fine front pleats, scattered gold motifs and a gold-trimmed neckline and cuffs. Paired with matching pink bottoms and a tasseled dupatta — the scarf that completes this three-piece set.",
      "detail": "Three pieces shown · Fine front pleats · Gold accents · Tasseled dupatta",
      "setContents": "Kurta, matching pink bottoms and tasseled dupatta (3 pieces)",
      "pieces": 3,
      "productType": "set",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [
        {"src":"assets/images/details/pink-three-piece-set/detail-1.webp","alt":"AI-derived close-up detail view of the pink three piece set showing neckline & trim.","label":"Neckline & Trim","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/pink-three-piece-set/detail-2.webp","alt":"AI-derived close-up detail view of the pink three piece set showing front motif detail.","label":"Front Motif Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/pink-three-piece-set/detail-3.webp","alt":"AI-derived close-up detail view of the pink three piece set showing sleeve cuff.","label":"Sleeve Cuff","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/pink-three-piece-set/detail-4.webp","alt":"AI-derived close-up detail view of the pink three piece set showing fabric & motifs.","label":"Fabric & Motifs","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/pink-three-piece-set/detail-5.webp","alt":"AI-derived close-up detail view of the pink three piece set showing bottoms detail.","label":"Bottoms Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/pink-three-piece-set/detail-6.webp","alt":"AI-derived close-up detail view of the pink three piece set showing dupatta detail.","label":"Dupatta Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ],
      "price": null,
      "availability": "unavailable",
      "isPreview": false
    },
    {
      "id": "navy-two-piece-set",
      "name": "Navy Two-Piece Kurta Set",
      "cardName": "Navy Kurta Set",
      "category": "Kurta sets",
      "color": "Navy & ivory",
      "colorHex": "#354b61",
      "image": "assets/images/navy-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a navy and ivory printed kurta with matching trousers, without a scarf. Fit and small details are illustrative.",
      "description": "Small ivory motifs and larger paisley details on a navy ground, finished with fine contrast piping and pleat details. Matching printed bottoms complete this two-piece set. No scarf or dupatta is included.",
      "detail": "Two pieces: kurta + bottoms · Floral & paisley print · No scarf / dupatta",
      "setContents": "Kurta and matching printed bottoms only (2 pieces; no scarf/dupatta)",
      "pieces": 2,
      "productType": "set",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [
        {"src":"assets/images/details/navy-two-piece-set/detail-1.webp","alt":"AI-derived close-up detail view of the navy two piece set showing neckline detail.","label":"Neckline Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/navy-two-piece-set/detail-2.webp","alt":"AI-derived close-up detail view of the navy two piece set showing front print detail.","label":"Front Print Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/navy-two-piece-set/detail-3.webp","alt":"AI-derived close-up detail view of the navy two piece set showing sleeve cuff.","label":"Sleeve Cuff","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/navy-two-piece-set/detail-4.webp","alt":"AI-derived close-up detail view of the navy two piece set showing paisley & print.","label":"Paisley & Print","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/navy-two-piece-set/detail-5.webp","alt":"AI-derived close-up detail view of the navy two piece set showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/navy-two-piece-set/detail-6.webp","alt":"AI-derived close-up detail view of the navy two piece set showing trouser detail.","label":"Trouser Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ],
      "price": null,
      "isPreview": false
    },
    {
      "id": "green-two-piece-set",
      "name": "Green Two-Piece Kurta Set",
      "cardName": "Green Kurta Set",
      "category": "Kurta sets",
      "color": "Olive green",
      "colorHex": "#a5af70",
      "image": "assets/images/green-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling preview of an adult woman wearing an olive-green kurta with a red floral neckline panel and coordinating plain green trousers, without a scarf. Fit and small details are illustrative.",
      "description": "An olive-green kurta with delicate red floral detail on its framed neckline panel and subtle dark cuff trim. Coordinating plain green bottoms complete the two-piece outfit. No scarf or dupatta is included.",
      "detail": "Two pieces: kurta + bottoms · Floral yoke detail · No scarf / dupatta",
      "setContents": "Kurta and coordinating plain green bottoms only (2 pieces; no scarf/dupatta)",
      "pieces": 2,
      "productType": "set",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [
        {"src":"assets/images/details/green-two-piece-set/detail-1.webp","alt":"AI-derived close-up detail view of the green two piece set showing embroidered yoke.","label":"Embroidered Yoke","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/green-two-piece-set/detail-2.webp","alt":"AI-derived close-up detail view of the green two piece set showing neckline detail.","label":"Neckline Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/green-two-piece-set/detail-3.webp","alt":"AI-derived close-up detail view of the green two piece set showing sleeve cuff.","label":"Sleeve Cuff","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/green-two-piece-set/detail-4.webp","alt":"AI-derived close-up detail view of the green two piece set showing floral motif.","label":"Floral Motif","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/green-two-piece-set/detail-5.webp","alt":"AI-derived close-up detail view of the green two piece set showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/green-two-piece-set/detail-6.webp","alt":"AI-derived close-up detail view of the green two piece set showing trouser detail.","label":"Trouser Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ],
      "price": null,
      "isPreview": false
    },
    {
      "id": "white-floral-two-piece-set",
      "name": "White Floral Two-Piece Set",
      "cardName": "White Floral Set",
      "category": "Co-ord sets",
      "color": "White, grey & teal",
      "colorHex": "#e4e3de",
      "description": "A white collared button-front shirt with an asymmetric floral panel and printed cuffs, paired with coordinating floral-hem trousers. Two pieces only: shirt and bottoms, with no scarf or dupatta.",
      "detail": "Two pieces: shirt + trousers · Floral panels · No scarf / dupatta",
      "setContents": "Button-front shirt and coordinating floral-hem trousers (2 pieces; no scarf/dupatta)",
      "pieces": 2,
      "productType": "set",
      "imageAlt": "AI-generated styling preview of an adult woman in a white floral-panel collared shirt and matching floral-hem trousers, without a scarf. Fit and details are illustrative.",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "image": "assets/images/white-floral-set-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "gallery": [
        {"src":"assets/images/details/white-floral-two-piece-set/detail-1.webp","alt":"AI-derived close-up detail view of the white floral two piece set showing collar detail.","label":"Collar Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/white-floral-two-piece-set/detail-2.webp","alt":"AI-derived close-up detail view of the white floral two piece set showing button front.","label":"Button Front","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/white-floral-two-piece-set/detail-3.webp","alt":"AI-derived close-up detail view of the white floral two piece set showing floral panel.","label":"Floral Panel","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/white-floral-two-piece-set/detail-4.webp","alt":"AI-derived close-up detail view of the white floral two piece set showing sleeve print.","label":"Sleeve Print","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/white-floral-two-piece-set/detail-5.webp","alt":"AI-derived close-up detail view of the white floral two piece set showing fabric & print.","label":"Fabric & Print","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/white-floral-two-piece-set/detail-6.webp","alt":"AI-derived close-up detail view of the white floral two piece set showing trouser hem.","label":"Trouser Hem","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ]
    },
    {
      "id": "yellow-floral-kurti",
      "name": "Yellow Short Kurti — Top Only",
      "cardName": "Yellow Kurti (Top Only)",
      "category": "Kurtas",
      "color": "Mustard yellow & white",
      "colorHex": "#b9a620",
      "description": "A short, hip/upper-thigh-length mustard-yellow kurti with white floral and paisley neckline detail, scattered motifs and decorated cuffs. This listing is for the kurti only. The model’s ivory trousers are styling only and are not included.",
      "detail": "Short kurti only · White floral detail · No bottoms or scarf included",
      "setContents": "Short yellow kurti only (1 piece); model styling trousers, footwear and scarf are not included",
      "pieces": 1,
      "productType": "kurti",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a short yellow floral kurti ending at the hips/upper thighs. The ivory trousers are styling only and are not included.",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "image": "assets/images/yellow-kurti-short-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "gallery": [
        {"src":"assets/images/details/yellow-floral-kurti/detail-1.webp","alt":"AI-derived close-up detail view of the yellow floral kurti showing neckline detail.","label":"Neckline Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/yellow-floral-kurti/detail-2.webp","alt":"AI-derived close-up detail view of the yellow floral kurti showing front motifs.","label":"Front Motifs","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/yellow-floral-kurti/detail-3.webp","alt":"AI-derived close-up detail view of the yellow floral kurti showing sleeve cuff.","label":"Sleeve Cuff","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/yellow-floral-kurti/detail-4.webp","alt":"AI-derived close-up detail view of the yellow floral kurti showing embroidery detail.","label":"Embroidery Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/yellow-floral-kurti/detail-5.webp","alt":"AI-derived close-up detail view of the yellow floral kurti showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/yellow-floral-kurti/detail-6.webp","alt":"AI-derived close-up detail view of the yellow floral kurti showing fabric texture.","label":"Fabric Texture","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ]
    },
    {
      "id": "dark-purple-three-piece-set",
      "name": "Dark Purple Three-Piece Kurta Set",
      "cardName": "Dark Purple Kurta Set",
      "category": "Kurta sets",
      "color": "Deep purple & white",
      "colorHex": "#3c254e",
      "description": "A deep-purple kurta with intricate white neckline and cuff details, coordinated with decorated-hem trousers and a dupatta with a white leafy-vine border. Three pieces: kurta, bottoms and scarf.",
      "detail": "Three pieces · White neckline and cuff detail · Leaf-border dupatta",
      "setContents": "Dark-purple kurta, decorated-hem bottoms and leaf-border dupatta (3 pieces)",
      "pieces": 3,
      "productType": "set",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a dark-purple kurta, white-detailed trouser hems and a matching leafy-border dupatta. Fit and details are illustrative.",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "image": "assets/images/dark-purple-set-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "availability": "unavailable",
      "isPreview": false,
      "gallery": [
        {"src":"assets/images/details/dark-purple-three-piece-set/detail-1.webp","alt":"AI-derived close-up detail view of the dark purple three piece set showing neckline embroidery.","label":"Neckline Embroidery","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-purple-three-piece-set/detail-2.webp","alt":"AI-derived close-up detail view of the dark purple three piece set showing front detail.","label":"Front Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-purple-three-piece-set/detail-3.webp","alt":"AI-derived close-up detail view of the dark purple three piece set showing sleeve cuff.","label":"Sleeve Cuff","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-purple-three-piece-set/detail-4.webp","alt":"AI-derived close-up detail view of the dark purple three piece set showing fabric & motifs.","label":"Fabric & Motifs","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-purple-three-piece-set/detail-5.webp","alt":"AI-derived close-up detail view of the dark purple three piece set showing trouser hem.","label":"Trouser Hem","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-purple-three-piece-set/detail-6.webp","alt":"AI-derived close-up detail view of the dark purple three piece set showing dupatta border.","label":"Dupatta Border","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ]
    },
    {
      "id": "plum-purple-three-piece-set",
      "name": "Plum Purple Three-Piece Kurta Set",
      "cardName": "Plum Purple Kurta Set",
      "category": "Kurta sets",
      "color": "Plum purple & white",
      "colorHex": "#77277e",
      "description": "A plum-purple kurta with a white paisley-floral neckline and scattered small flower details. Coordinating bottoms with a narrow white trim and a small-flower dupatta complete the three-piece set.",
      "detail": "Three pieces · White paisley-floral neckline · Small-flower dupatta",
      "setContents": "Plum-purple kurta, narrow-trim bottoms and small-flower dupatta (3 pieces)",
      "pieces": 3,
      "productType": "set",
      "imageAlt": "AI-generated styling preview of an adult woman wearing a plum-purple kurta with white paisley-floral detail, coordinating trousers and a small-flower dupatta. Fit and details are illustrative.",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "image": "assets/images/plum-purple-set-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "availability": "unavailable",
      "isPreview": false,
      "gallery": [
        {"src":"assets/images/details/plum-purple-three-piece-set/detail-1.webp","alt":"AI-derived close-up detail view of the plum purple three piece set showing neckline detail.","label":"Neckline Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/plum-purple-three-piece-set/detail-2.webp","alt":"AI-derived close-up detail view of the plum purple three piece set showing front motifs.","label":"Front Motifs","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/plum-purple-three-piece-set/detail-3.webp","alt":"AI-derived close-up detail view of the plum purple three piece set showing sleeve cuff.","label":"Sleeve Cuff","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/plum-purple-three-piece-set/detail-4.webp","alt":"AI-derived close-up detail view of the plum purple three piece set showing fabric & motifs.","label":"Fabric & Motifs","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/plum-purple-three-piece-set/detail-5.webp","alt":"AI-derived close-up detail view of the plum purple three piece set showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/plum-purple-three-piece-set/detail-6.webp","alt":"AI-derived close-up detail view of the plum purple three piece set showing dupatta detail.","label":"Dupatta Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ]
    },
    {
      "id": "olive-lattice-short-kurti",
      "name": "Olive Lattice Short Kurti — Top Only",
      "cardName": "Olive Short Kurti",
      "color": "Olive green",
      "colorHex": "#657532",
      "description": "A short olive-green kurti with lattice-textured chest panels, small white accents and buttons, and white paisley sleeve details. Hip/upper-thigh length. Top only; the model’s ivory trousers and footwear are styling props and are not included.",
      "detail": "Short top only · Lattice-textured front · White sleeve detail",
      "category": "Kurtas",
      "image": "assets/images/olive-lattice-short-kurti-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "imageAlt": "AI-generated styling view of an adult woman wearing the olive green short kurti at hip/upper-thigh length. The ivory trousers are styling only, not included.",
      "setContents": "Olive green short kurti only (1 piece); styling trousers and footwear are not included. No scarf included",
      "pieces": 1,
      "productType": "kurti",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "gallery": [
        {"src":"assets/images/details/olive-lattice-short-kurti/detail-1.webp","alt":"AI-derived close-up detail view of the olive lattice short kurti showing chest embroidery.","label":"Chest Embroidery","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/olive-lattice-short-kurti/detail-2.webp","alt":"AI-derived close-up detail view of the olive lattice short kurti showing neckline detail.","label":"Neckline Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/olive-lattice-short-kurti/detail-3.webp","alt":"AI-derived close-up detail view of the olive lattice short kurti showing sleeve embroidery.","label":"Sleeve Embroidery","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/olive-lattice-short-kurti/detail-4.webp","alt":"AI-derived close-up detail view of the olive lattice short kurti showing lattice pattern.","label":"Lattice Pattern","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/olive-lattice-short-kurti/detail-5.webp","alt":"AI-derived close-up detail view of the olive lattice short kurti showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/olive-lattice-short-kurti/detail-6.webp","alt":"AI-derived close-up detail view of the olive lattice short kurti showing fabric texture.","label":"Fabric Texture","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ]
    },
    {
      "id": "slate-grey-short-kurti",
      "name": "Slate Grey Short Kurti — Top Only",
      "cardName": "Grey Short Kurti",
      "color": "Slate grey",
      "colorHex": "#495963",
      "description": "A short slate-grey kurti with dark tone-on-tone neckline detailing, tie tassels and scattered decorative motifs. Hip/upper-thigh length. Top only; the model’s ivory trousers and footwear are styling props and are not included.",
      "detail": "Short top only · Tone-on-tone detail · Neck ties",
      "category": "Kurtas",
      "image": "assets/images/slate-grey-short-kurti-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "imageAlt": "AI-generated styling view of an adult woman wearing the slate grey short kurti at hip/upper-thigh length. The ivory trousers are styling only, not included.",
      "setContents": "Slate grey short kurti only (1 piece); styling trousers and footwear are not included. No scarf included",
      "pieces": 1,
      "productType": "kurti",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "gallery": [
        {"src":"assets/images/details/slate-grey-short-kurti/detail-1.webp","alt":"AI-derived close-up detail view of the slate grey short kurti showing neckline detail.","label":"Neckline Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/slate-grey-short-kurti/detail-2.webp","alt":"AI-derived close-up detail view of the slate grey short kurti showing chest embroidery.","label":"Chest Embroidery","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/slate-grey-short-kurti/detail-3.webp","alt":"AI-derived close-up detail view of the slate grey short kurti showing sleeve detail.","label":"Sleeve Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/slate-grey-short-kurti/detail-4.webp","alt":"AI-derived close-up detail view of the slate grey short kurti showing front motif.","label":"Front Motif","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/slate-grey-short-kurti/detail-5.webp","alt":"AI-derived close-up detail view of the slate grey short kurti showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/slate-grey-short-kurti/detail-6.webp","alt":"AI-derived close-up detail view of the slate grey short kurti showing fabric texture.","label":"Fabric Texture","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ]
    },
    {
      "id": "wine-floral-short-kurti",
      "name": "Wine Floral Short Kurti — Top Only",
      "cardName": "Wine Short Kurti",
      "color": "Wine purple",
      "colorHex": "#792244",
      "description": "A short wine-purple kurti with a pale floral chest motif, a notched neckline and fine coordinating cuff trim. Hip/upper-thigh length. Top only; the model’s ivory trousers and footwear are styling props and are not included.",
      "detail": "Short top only · Floral neckline detail · Fine cuff trim",
      "category": "Kurtas",
      "image": "assets/images/wine-floral-short-kurti-model.webp",
      "imageKind": "ai-model",
      "price": null,
      "isPreview": false,
      "imageAlt": "AI-generated styling view of an adult woman wearing the wine purple short kurti at hip/upper-thigh length. The ivory trousers are styling only, not included.",
      "setContents": "Wine purple short kurti only (1 piece); styling trousers and footwear are not included. No scarf included",
      "pieces": 1,
      "productType": "kurti",
      "photoNote": "This is a short, top-only kurti. The model’s trousers and footwear are styling props, not included merchandise. This image is AI-generated styling; exact fit and garment details should be confirmed with the store.",
      "gallery": [
        {"src":"assets/images/details/wine-floral-short-kurti/detail-1.webp","alt":"AI-derived close-up detail view of the wine floral short kurti showing neckline embroidery.","label":"Neckline Embroidery","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/wine-floral-short-kurti/detail-2.webp","alt":"AI-derived close-up detail view of the wine floral short kurti showing floral chest detail.","label":"Floral Chest Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/wine-floral-short-kurti/detail-3.webp","alt":"AI-derived close-up detail view of the wine floral short kurti showing sleeve cuff.","label":"Sleeve Cuff","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/wine-floral-short-kurti/detail-4.webp","alt":"AI-derived close-up detail view of the wine floral short kurti showing fabric & flowers.","label":"Fabric & Flowers","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/wine-floral-short-kurti/detail-5.webp","alt":"AI-derived close-up detail view of the wine floral short kurti showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/wine-floral-short-kurti/detail-6.webp","alt":"AI-derived close-up detail view of the wine floral short kurti showing threadwork close-up.","label":"Threadwork Close-Up","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ]
    },
    {
      "id": "dark-green-floral-two-piece-set",
      "name": "Dark Green Floral Two-Piece Kurta Set",
      "cardName": "Dark Green Floral Set",
      "category": "Kurta sets",
      "color": "Deep green & floral",
      "colorHex": "#164b4c",
      "image": "assets/images/dark-green-floral-set-model.webp",
      "imageKind": "ai-model",
      "imageAlt": "AI-generated styling view of an adult woman in a long dark-green button-front floral kurta and matching plain trousers, without a scarf. Fit and details are illustrative.",
      "description": "A longer dark-green button-front kurta with fine chest pleats and pink-and-yellow floral panels, paired with coordinating plain trousers. Shown as a two-piece outfit: kurta and bottoms, with no scarf pictured. Please confirm availability and final garment details when ordering.",
      "detail": "Long kurta + plain trousers · Floral panels · No scarf shown",
      "setContents": "Long floral kurta and coordinating plain trousers (2 pieces as photographed; no scarf shown)",
      "pieces": 2,
      "productType": "set",
      "photoNote": "This image is AI-generated styling. Fit, length, drape and small details are approximate. Please confirm actual garment details, prices and availability with Sutras before ordering.",
      "gallery": [
        {"src":"assets/images/details/dark-green-floral-two-piece-set/detail-1.webp","alt":"AI-derived close-up detail view of the dark green floral two piece set showing button front.","label":"Button Front","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-green-floral-two-piece-set/detail-2.webp","alt":"AI-derived close-up detail view of the dark green floral two piece set showing collar detail.","label":"Collar Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-green-floral-two-piece-set/detail-3.webp","alt":"AI-derived close-up detail view of the dark green floral two piece set showing floral sleeve.","label":"Floral Sleeve","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-green-floral-two-piece-set/detail-4.webp","alt":"AI-derived close-up detail view of the dark green floral two piece set showing side floral panel.","label":"Side Floral Panel","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-green-floral-two-piece-set/detail-5.webp","alt":"AI-derived close-up detail view of the dark green floral two piece set showing hem detail.","label":"Hem Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."},
        {"src":"assets/images/details/dark-green-floral-two-piece-set/detail-6.webp","alt":"AI-derived close-up detail view of the dark green floral two piece set showing trouser detail.","label":"Trouser Detail","kind":"ai-detail","caption":"AI-derived detail view from the modelled garment image; use as a visual guide and confirm exact garment details with Sutras."}
      ],
      "price": null,
      "isPreview": false
    }
  ]
};
